services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: farmacia-escola-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DATABASE_URL=file:./prisma/dev.db
      - JWT_SECRET=farmacia_escola_secret_key_desenvolvimento_2026
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend-prisma-data:/app/prisma
    networks:
      - farmacia-network
    command: sh -c "npx prisma db push && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: farmacia-escola-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - INTERNAL_API_URL=http://backend:3001
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - farmacia-network

volumes:
  backend-prisma-data:
    driver: local

networks:
  farmacia-network:
    driver: bridge